# Generated by Django 6.0.3 on 2026-03-27 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_location_alter_experience_category_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='pricingrule',
            old_name='experience_id',
            new_name='experience',
        ),
        migrations.RenameIndex(
            model_name='pricingrule',
            new_name='pricing_rul_experie_86bb9f_idx',
            old_name='pricing_rul_experie_b1ed9e_idx',
        ),
    ]
